# Generated by Django 4.2.13 on 2024-07-24 15:24

import anchor.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file',
            field=anchor.models.fields.BlobField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+'),
        ),
    ]
