# Generated by Django 4.2.13 on 2024-07-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
